### ISSUE TITLE
Avbin not working for any install?

### ISSUE THREAD

**Issue by pvcraven** [pvcraven/arcade#105]
Issue #64 is related to this I believe.

I did installs of Arcade on computers in our lab, and had students install Arcade on their laptops. None of them worked because avbin was missing. My Mac students also could not run because avbin was missing.

I also can't get avbin to install on a mac from the official download site. It gets most of the way through the installation and then errors out.

At one point we had this working, and a separate install was not required. I'm not sure when this broke.

**Comment by danboid** [comment]
As I mentioned in https://github.com/pvcraven/arcade/issues/98, I have been unable to get avbin to work under Linux with arcade whenever I have built it myself and the author of avbin hasn't responded to my bug report / request for build instructions. Not a good sign.

https://github.com/AVbin/AVbin/issues/64

As a result I have had to postpone my arcade project. I hope the avbin dependency can be resolved because arcade looks like it could be a great replacement for pygame but so long as it depends upon avbin, using it is not an option for me.

**Comment by pauleveritt** [comment]
Just out of curiosity, does your game use audio?

—Paul

**Comment by danboid** [comment]
Yes. Any game I make will use audio and I think that that will apply to most game projects under any platform/language/library. Of course, arcade depends upon avbin for audio playback so arcade isn't fit for purpose yet for me.

**Comment by pvcraven** [comment]
Looks like pyglet updated where they expected dlls to be or something.

**Comment by pvcraven** [comment]
New version released that should work with Windows. Hopefully I can try working on the Mac tomorrow.

**Comment by danboid** [comment]
Good to hear some progress with this - hopefully it will fix it under (Arch) Linux too.

**Comment by pauleveritt** [comment]
I just fired up a new macOS Sierra in Parallels, so I could really isolate things. I used a Python 3.6 binary from python.org <http://python.org/>. I then did pip install arcade (and got 1.0.1post2) which got pyglet 1.2.4

And boy were things weird. Importing arcade failed:

import arcade
Traceback (most recent call last):
  File "/Users/pauleveritt/PycharmProjects/arcade/env36/lib/python3.6/site-packages/pyglet/__init__.py", line 351, in __getattr__
    return getattr(self._module, name)
AttributeError: 'NoneType' object has no attribute 'Window'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/pauleveritt/PycharmProjects/arcade/env36/lib/python3.6/site-packages/arcade/__init__.py", line 14, in <module>
    from arcade.application import *
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/pauleveritt/PycharmProjects/arcade/env36/lib/python3.6/site-packages/arcade/application.py", line 14, in <module>
    class Window(pyglet.window.Window):
  File "/Users/pauleveritt/PycharmProjects/arcade/env36/lib/python3.6/site-packages/pyglet/__init__.py", line 357, in __getattr__
    __import__(import_name)
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/pauleveritt/PycharmProjects/arcade/env36/lib/python3.6/site-packages/pyglet/window/__init__.py", line 1816, in <module>
    gl._create_shadow_window()
  File "/Users/pauleveritt/PycharmProjects/arcade/env36/lib/python3.6/site-packages/pyglet/gl/__init__.py", line 205, in _create_shadow_window
    _shadow_window = Window(width=1, height=1, visible=False)
  File "/Users/pauleveritt/PycharmProjects/arcade/env36/lib/python3.6/site-packages/pyglet/window/__init__.py", line 509, in __init__
    raise NoSuchConfigException('No standard config is available.')
pyglet.window.NoSuchConfigException: No standard config is available.


—Paul

**Comment by pvcraven** [comment]
That's weird. My students' computers were able to import arcade and do everything but sound. But this is failing just on the import. It looks like around the OpenGL support. Could Parallels not support OpenGL?

**Comment by pauleveritt** [comment]
At first I thought it was because I stupidly named my project directory “arcade”. :)

I changed that but it didn’t have an effect. FWIW, I don’t have Xcode installed.

—Paul

**Comment by pauleveritt** [comment]
My guess is that, because I’m running in Parallels with macOS as a guest, it is emulating a video card which can’t do OpenGL.

—Paul

**Comment by pvcraven** [comment]
Macs can now play .wav files.

**Comment by pvcraven** [comment]
It looks like Pyglet is going with ffmpeg, so I don't think we'll sink more time into this one.

 https://groups.google.com/forum/#!topic/pyglet-users/ah2I54BSrZg
