### ISSUE TITLE
physics_app_2.py got error

### ISSUE THREAD

**Issue by VictorTagayun** [pvcraven/arcade#119]
Traceback (most recent call last):
  File "E:\Hobby\Python\Games\Arcade\examples\physics_app_2.py", line 97, in <module>
    window = MyApplication(1024, 800)
  File "E:\Hobby\Python\Games\Arcade\examples\physics_app_2.py", line 33, in __init__
    self.player = arcade.PhysicsAABB("images/character.png", [390, 400], [79 / 2, 125 / 2], [0, 0], .7, 3, 0.4)
AttributeError: module 'arcade' has no attribute 'PhysicsAABB'

**Comment by pvcraven** [comment]
This example is out of date and needs to be removed.

**Comment by pvcraven** [comment]
Hm, looks like it was already removed a while ago. Closing issue.
