### ISSUE TITLE
TravisCI not working

### ISSUE THREAD

**Issue by pvcraven** [pvcraven/arcade#142]
Line continuation character being ignored?

```
======================================================================
FAIL: load_textures (arcade.draw_commands)
Doctest: arcade.draw_commands.load_textures
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/python/3.6.3/lib/python3.6/doctest.py", line 2199, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for arcade.draw_commands.load_textures
  File "/home/travis/build/pvcraven/arcade/arcade/draw_commands.py", line 104, in load_textures
----------------------------------------------------------------------
File "/home/travis/build/pvcraven/arcade/arcade/draw_commands.py", line 159, in arcade.draw_commands.load_textures
Failed example:
    texture_info_list = arcade.load_textures("examples/images/character_sheet.png",
Exception raised:
    Traceback (most recent call last):
      File "/opt/python/3.6.3/lib/python3.6/doctest.py", line 1330, in __run
        compileflags, 1), test.globs)
      File "<doctest arcade.draw_commands.load_textures[15]>", line 1
        texture_info_list = arcade.load_textures("examples/images/character_sheet.png",
                                                                                      ^
    SyntaxError: unexpected EOF while parsing
```

**Comment by pvcraven** [comment]
Fixed.
