### ISSUE TITLE
Sprite images missing from animated sprite example

### ISSUE THREAD

**Issue by pvcraven** [pvcraven/arcade#214]
For the animated feet example, the character_sprites directory is missing in the images directory.

`
  Traceback (most recent call last):
    File "C:\Program Files (x86)\Python36-32\Lib\site-packages\arcade\examples\sprite_move_animation.py", line 178, in <module>
      main()
    File "C:\Program Files (x86)\Python36-32\Lib\site-packages\arcade\examples\sprite_move_animation.py", line 173, in main
      window.setup()
    File "C:\Program Files (x86)\Python36-32\Lib\site-packages\arcade\examples\sprite_move_animation.py", line 61, in setup
      scale=character_scale))
    File "C:\Program Files (x86)\Python36-32\lib\site-packages\arcade\draw_commands.py", line 285, in load_texture
      source_image = PIL.Image.open(file_name)
    File "C:\Program Files (x86)\Python36-32\lib\site-packages\PIL\Image.py", line 2548, in open
      fp = builtins.open(filename, "rb")
  FileNotFoundError: [Errno 2] No such file or directory: 'images/character_sprites/character0.png'
`

**Comment by jgrantdev** [comment]
I can not reproduce this.

I see the files in the appropriate place in the repo.

**Comment by pvcraven** [comment]
Closed with release of 1.3.4 on 28-May-2018.
