### ISSUE TITLE
ver. 1.3.4: Asteroid Example Crashes When Playing Sound

### ISSUE THREAD

**Issue by pybokeh** [pvcraven/arcade#224]
## Bug Report
Crash
Traceback (most recent call last):
  File "/opt/python3.6.4/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/python3.6.4/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pybokeh/envs/gamedev/lib/python3.6/site-packages/arcade/examples/asteroid_smasher.py", line 385, in <module>
    main()
  File "/home/pybokeh/envs/gamedev/lib/python3.6/site-packages/arcade/examples/asteroid_smasher.py", line 381, in main
    arcade.run()
  File "/home/pybokeh/envs/gamedev/lib/python3.6/site-packages/arcade/window_commands.py", line 191, in run
    pyglet.app.run()
  File "/home/pybokeh/envs/gamedev/lib/python3.6/site-packages/pyglet/app/__init__.py", line 138, in run
    event_loop.run()
  File "/home/pybokeh/envs/gamedev/lib/python3.6/site-packages/pyglet/app/base.py", line 142, in run
    self._run()
  File "/home/pybokeh/envs/gamedev/lib/python3.6/site-packages/pyglet/app/base.py", line 155, in _run
    platform_event_loop.step(timeout)
  File "/home/pybokeh/envs/gamedev/lib/python3.6/site-packages/pyglet/app/xlib.py", line 125, in step
    device.select()
  File "/home/pybokeh/envs/gamedev/lib/python3.6/site-packages/pyglet/canvas/xlib.py", line 168, in select
    dispatch(e)
  File "/home/pybokeh/envs/gamedev/lib/python3.6/site-packages/pyglet/window/xlib/__init__.py", line 922, in dispatch_platform_event_view
    event_handler(e)
  File "/home/pybokeh/envs/gamedev/lib/python3.6/site-packages/pyglet/window/xlib/__init__.py", line 1089, in _event_key_view
    self.dispatch_event('on_key_press', symbol, modifiers)
  File "/home/pybokeh/envs/gamedev/lib/python3.6/site-packages/pyglet/window/__init__.py", line 1232, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "/home/pybokeh/envs/gamedev/lib/python3.6/site-packages/pyglet/event.py", line 367, in dispatch_event
    if getattr(self, event_type)(*args):
  File "/home/pybokeh/envs/gamedev/lib/python3.6/site-packages/arcade/examples/asteroid_smasher.py", line 256, in on_key_press
    arcade.play_sound(self.laser_sound)
  File "/home/pybokeh/envs/gamedev/lib/python3.6/site-packages/arcade/sound.py", line 139, in _playsound_unix
    sound.play()
  File "/home/pybokeh/envs/gamedev/lib/python3.6/site-packages/pyglet/media/sources/base.py", line 269, in play
    player.queue(self)
  File "/home/pybokeh/envs/gamedev/lib/python3.6/site-packages/pyglet/media/player.py", line 100, in queue
    group.queue(source)
  File "/home/pybokeh/envs/gamedev/lib/python3.6/site-packages/pyglet/media/sources/base.py", line 499, in queue
    source = source._get_queue_source()
  File "/home/pybokeh/envs/gamedev/lib/python3.6/site-packages/pyglet/media/sources/base.py", line 377, in _get_queue_source
    raise MediaException('This source is already queued on a player.')
pyglet.media.exceptions.MediaException: This source is already queued on a player.
python: ../nptl/pthread_mutex_lock.c:361: __pthread_mutex_lock_full: Assertion `robust || (oldval & FUTEX_OWNER_DIED) == 0' failed.
Aborted

### Actual behavior:
Asteroid smasher game smashed when I hit space/play sound

### Expected behavior:
Not crash

### Steps to reproduce/example code:
Run the asteroid smasher example: python -m arcade.examples.asteroid_smasher

**Comment by pvcraven** [comment]
Closing.
