### ISSUE TITLE
Question: Using Bee Briefcase to make iOS app

### ISSUE THREAD

**Issue by Mr-Coxall** [pvcraven/arcade#234]
## Question:

 I am able to use the Bee Briefcase (https://briefcase.readthedocs.io/en/latest/index.html) to make an iOS app using Python code. I was wondering how I would go about adding in the Arcade Library to the Xcode code so that I could build iOS games using Arcade?

**Comment by Mr-Coxall** [comment]
I did find this (http://arcade.academy/distribute_macos.html)
I used it to try and include the arcade library into the Xcode project that Briefcase makes.
The build does seem to work but when you compile the Xcode project, I get the following error:

2018-06-10 19:26:06.644349-0400 iOS Test[2576:290213] PythonHome is: /Users/pcoxall/Library/Developer/CoreSimulator/Devices/DF91A2FF-8FBF-4FBD-BAB7-694842CA01A2/data/Containers/Bundle/Application/30F94AAD-0B76-47FD-9830-2016F4356A48/iOS Test.app/Library/Python
2018-06-10 19:26:06.646114-0400 iOS Test[2576:290213] PYTHONPATH is: PYTHONPATH=/Users/pcoxall/Library/Developer/CoreSimulator/Devices/DF91A2FF-8FBF-4FBD-BAB7-694842CA01A2/data/Containers/Bundle/Application/30F94AAD-0B76-47FD-9830-2016F4356A48/iOS Test.app/Library/Application Support/com.example.iOSTest/app:/Users/pcoxall/Library/Developer/CoreSimulator/Devices/DF91A2FF-8FBF-4FBD-BAB7-694842CA01A2/data/Containers/Bundle/Application/30F94AAD-0B76-47FD-9830-2016F4356A48/iOS Test.app/Library/Application Support/com.example.iOSTest/app_packages
2018-06-10 19:26:06.646540-0400 iOS Test[2576:290213] Initializing Python runtime
2018-06-10 19:26:06.764591-0400 iOS Test[2576:290213] Running /Users/pcoxall/Library/Developer/CoreSimulator/Devices/DF91A2FF-8FBF-4FBD-BAB7-694842CA01A2/data/Containers/Bundle/Application/30F94AAD-0B76-47FD-9830-2016F4356A48/iOS Test.app/Library/Application Support/com.example.iOSTest/app/iOSTest/__main__.py
Traceback (most recent call last):
  File "/Users/pcoxall/Library/Developer/CoreSimulator/Devices/DF91A2FF-8FBF-4FBD-BAB7-694842CA01A2/data/Containers/Bundle/Application/30F94AAD-0B76-47FD-9830-2016F4356A48/iOS Test.app/Library/Application Support/com.example.iOSTest/app/iOSTest/__main__.py", line 1, in <module>
    from iOSTest.app import main
  File "/Users/pcoxall/Library/Developer/CoreSimulator/Devices/DF91A2FF-8FBF-4FBD-BAB7-694842CA01A2/data/Containers/Bundle/Application/30F94AAD-0B76-47FD-9830-2016F4356A48/iOS Test.app/Library/Application Support/com.example.iOSTest/app/iOSTest/app.py", line 1, in <module>
    import arcade
  File "/Users/pcoxall/Library/Developer/CoreSimulator/Devices/DF91A2FF-8FBF-4FBD-BAB7-694842CA01A2/data/Containers/Bundle/Application/30F94AAD-0B76-47FD-9830-2016F4356A48/iOS Test.app/Library/Application Support/com.example.iOSTest/app_packages/arcade/__init__.py", line 15, in <module>
    from arcade.application import *
  File "/Users/pcoxall/Library/Developer/CoreSimulator/Devices/DF91A2FF-8FBF-4FBD-BAB7-694842CA01A2/data/Containers/Bundle/Application/30F94AAD-0B76-47FD-9830-2016F4356A48/iOS Test.app/Library/Application Support/com.example.iOSTest/app_packages/arcade/application.py", line 8, in <module>
    from arcade.window_commands import set_viewport
  File "/Users/pcoxall/Library/Developer/CoreSimulator/Devices/DF91A2FF-8FBF-4FBD-BAB7-694842CA01A2/data/Containers/Bundle/Application/30F94AAD-0B76-47FD-9830-2016F4356A48/iOS Test.app/Library/Application Support/com.example.iOSTest/app_packages/arcade/window_commands.py", line 11, in <module>
    import pyglet.gl as gl
  File "/Users/pcoxall/Library/Developer/CoreSimulator/Devices/DF91A2FF-8FBF-4FBD-BAB7-694842CA01A2/data/Containers/Bundle/Application/30F94AAD-0B76-47FD-9830-2016F4356A48/iOS Test.app/Library/Application Support/com.example.iOSTest/app_packages/pyglet/gl/__init__.py", line 100, in <module>
    from pyglet.gl.lib import GLException
  File "/Users/pcoxall/Library/Developer/CoreSimulator/Devices/DF91A2FF-8FBF-4FBD-BAB7-694842CA01A2/data/Containers/Bundle/Application/30F94AAD-0B76-47FD-9830-2016F4356A48/iOS Test.app/Library/Application Support/com.example.iOSTest/app_packages/pyglet/gl/lib.py", line 143, in <module>
    from pyglet.gl.lib_glx import link_GL, link_GLU, link_GLX
  File "/Users/pcoxall/Library/Developer/CoreSimulator/Devices/DF91A2FF-8FBF-4FBD-BAB7-694842CA01A2/data/Containers/Bundle/Application/30F94AAD-0B76-47FD-9830-2016F4356A48/iOS Test.app/Library/Application Support/com.example.iOSTest/app_packages/pyglet/gl/lib_glx.py", line 50, in <module>
    gl_lib = pyglet.lib.load_library('GL')
  File "/Users/pcoxall/Library/Developer/CoreSimulator/Devices/DF91A2FF-8FBF-4FBD-BAB7-694842CA01A2/data/Containers/Bundle/Application/30F94AAD-0B76-47FD-9830-2016F4356A48/iOS Test.app/Library/Application Support/com.example.iOSTest/app_packages/pyglet/lib.py", line 158, in load_library
    raise ImportError('Library "%s" not found.' % names[0])
ImportError: Library "GL" not found.
2018-06-10 19:26:07.168226-0400 iOS Test[2576:290213] Application quit abnormally!
2018-06-10 19:26:07.175974-0400 iOS Test[2576:290213] Leaving

I am not sure what the :
            ImportError: Library "GL" not found.
error is pointing to.

**Comment by pvcraven** [comment]
GL refers to the OpenGL library. I'm not sure about iOS support for OpenGL. I know MacOS has deprecated support for OpenGL which is annoying.

**Comment by pvcraven** [comment]
Looks like Kivy uses OpenGL ES 2 to target mobile platforms. So the code might not totally off-base to adapt to mobile. It would require a bit of effort to research still, and I don't see doing that myself any time soon.

**Comment by Mr-Coxall** [comment]
Thanks so much for getting back to me.
If you ever do get it working for iOS and Mac, please let me know.
I would love to use it with my grade 11 programming students.

Should the "Build for MacOS" section be removed, since it does not actually build for Mac any more?
(http://arcade.academy/distribute_macos.html)
