### ISSUE TITLE
Arcade not finding avbin when using inside virtualenv

### ISSUE THREAD

**Issue by MushroomMaula** [pvcraven/arcade#249]
## Bug Report
I was trying the [Collect Coins Example](http://arcade.academy/examples/sprite_move_keyboard.html#sprite-move-keyboard) and when trying to execute i get this error

    Traceback (most recent call last):
      File "c:\Users\Ruth\Desktop\Max Anwendungen\Python Codes\Projects\Python RPG\game.py", line 1, in <module>
        import arcade
      File "c:\Users\Ruth\Desktop\Max Anwendungen\Python Codes\Projects\Python RPG\venv\lib\site-packages\arcade\__init__.py", line 21, in <module>
        from arcade.sound import *
      File "c:\Users\Ruth\Desktop\Max Anwendungen\Python Codes\Projects\Python RPG\venv\lib\site-packages\arcade\sound.py", line 193, in <module>
        _load_sound_library()
      File "c:\Users\Ruth\Desktop\Max Anwendungen\Python Codes\Projects\Python RPG\venv\lib\site-packages\arcade\sound.py", line 70, in _load_sound_library
        pyglet.lib.load_library(path)
      File "c:\Users\Ruth\Desktop\Max Anwendungen\Python Codes\Projects\Python RPG\venv\lib\site-packages\pyglet\lib.py", line 158, in load_library
        raise ImportError('Library "%s" not found.' % names[0])
    ImportError: Library "Win32/avbin" not found.

### Actual behavior:
Arcade is not finding the module
### Expected behavior:
Arcade should find the module
### Steps to reproduce/example code:
create an virtualenv 
`virtualenv venv`
`cd venv\Scripts`
`activate.bat`
`pip install arcade`
`python -m arcade.examples.sprite_move_keyboard`

### What should be added/changed?
change 

```python
import site
if hasattr(site, 'getsitepackages'):
    packages = site.getsitepackages()

    if appveyor:
        if is64bit:
            path = "Win64/avbin"
        else:
            path = "Win32/avbin"

    else:
        if is64bit:
            path = packages[0] + "/lib/site-packages/arcade/Win64/avbin"
        else:
            path = packages[0] + "/lib/site-packages/arcade/Win32/avbin"

else:
    if is64bit:
        path = "Win64/avbin"
    else:
        path = "Win32/avbin"
```
to this

```python
from distutils.sysconfig import get_python_lib
site_pkg_path = get_python_lib()
if appveyor:
    if is64bit:
        path = "Win64/avbin"
    else:
        path = "Win32/avbin"

else:
    if is64bit:
        path = os.path.join(site_pkg_path, r"arcade\Win64\avbin")
    else:
        path = os.path.join(site_pkg_path, r"arcade\Win32\avbin")
```

**Comment by pvcraven** [comment]
Closed with 2.0 release.
