### ISSUE TITLE
"How to Compile" docs don't work with code currently on master

### ISSUE THREAD

**Issue by SirGnip** [pvcraven/arcade#293]
I'm a newcomer to arcade and would like to start contributing.  So, I started working step by step through the "[How to Contribute](http://arcade.academy/how_to_contribute.html)" docs and I started having problems getting things building (missing dependencies, "make" script syntax changes, etc.).  I did get things working after a bit of troubleshooting, so I'm fixing the "contribution" docs to reflect what worked for me.  I also made some other minor doc fixes while I was looking at things.  I should have a PR up soon.

I am currently using a fork with f5dae68 as HEAD.  Also, I am on Windows and tested building the docs and running a few of the arcade example programs.  I did NOT test anything on Linux.

### A sampling of the errors I ran into while following the docs to get a build working...

Based on the docs online, I expected "make" to build everything. It gave me some nice help instead:
```
(aenv2) C:\_other\repos\arcade>make
make test        - Runs the tests
make dist        - Make the distributables
make full        - Builds the project, installs it, builds
                   documentation, runs unit tests.
make doc           Builds the documentation. Documentation
                   will be in doc/build/html
make fast        - Builds and installs the library WITHOUT unit
                   tests.
make deploy_pypi - Deploy to PyPi (if you have environment
                   variables set up correctly.)
make deploy_docs - Deploy documentation to S3 bucket (if you
                   have environment variables set up.)
```

I expected "makefast" to compile the code.  It didn't:
```
(aenv2) C:\_other\repos\arcade>makefast
'makefast' is not recognized as an internal or external command,
operable program or batch file.
```

I expected "makedoc" to generate the docs.  It didn't:
```
(aenv2) C:\_other\repos\arcade>makedoc
'makedoc' is not recognized as an internal or external command,
operable program or batch file.
```

I expected to be able to run an example program directly from the repo.  It failed (was missing a couple dependencies):
```
(aenv4) C:\_other\repos\arcade>python -m arcade.examples.happy_face
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 183, in 

_run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 109, in 

_get_module_details
    __import__(pkg_name)
  File "C:\_other\repos\arcade\arcade\__init__.py", line 20, in <module>
    from arcade.draw_commands import *
  File "C:\_other\repos\arcade\arcade\draw_commands.py", line 12, in <module>
    import PIL.Image
ModuleNotFoundError: No module named 'PIL'
```

Running "make test" failed saying it was missing "pytest":
```
(aenv3) C:\_other\repos\arcade>make test
running test
running egg_info
writing arcade.egg-info\PKG-INFO
writing dependency_links to arcade.egg-info\dependency_links.txt
writing requirements to arcade.egg-info\requires.txt
writing top-level names to arcade.egg-info\top_level.txt
reading manifest file 'arcade.egg-info\SOURCES.txt'
writing manifest file 'arcade.egg-info\SOURCES.txt'
running build_ext
tests (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\unittest\loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "c:\_other\repos\arcade\tests\__init__.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'


----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
Test failed: <unittest.runner.TextTestResult run=1 errors=1 failures=0>
Coverage.py warning: No data was collected. (no-data-collected)
error: Test failed: <unittest.runner.TextTestResult run=1 errors=1 failures=0>
```
 (Installing pytest got things a little farther, but it appears the tests are still failing)

**Comment by pvcraven** [comment]
Deployed.
