### ISSUE TITLE
NoSuchConfig on window creation

### ISSUE THREAD

**Issue by mbartelsm** [pvcraven/arcade#340]
### Actual behavior: 
Window is not created

### Expected behavior:
Window is created

Code:
```python
import arcade

arcade.open_window(800,600, "Drawing sample")
```

Error:
```shell
Traceback (most recent call last):
  File "D:/Projects/Coding/Python/Arcade_learning/samples/drawing_sample.py", line 3, in <module>
    arcade.open_window(800,600, "Drawing sample")
  File "D:\Projects\Coding\Python\Arcade_learning\venv\lib\site-packages\arcade\application.py", line 384, in open_window
    _window = Window(width, height, window_title, resizable, update_rate=None)
  File "D:\Projects\Coding\Python\Arcade_learning\venv\lib\site-packages\arcade\application.py", line 53, in __init__
    resizable=resizable, config=config)
  File "D:\Projects\Coding\Python\Arcade_learning\venv\lib\site-packages\pyglet\window\win32\__init__.py", line 137, in __init__
    super(Win32Window, self).__init__(*args, **kwargs)
  File "D:\Projects\Coding\Python\Arcade_learning\venv\lib\site-packages\pyglet\window\__init__.py", line 592, in __init__
    config = screen.get_best_config(config)
  File "D:\Projects\Coding\Python\Arcade_learning\venv\lib\site-packages\pyglet\canvas\base.py", line 197, in get_best_config
    raise window.NoSuchConfigException()
pyglet.window.NoSuchConfigException
```

**Comment by pvcraven** [comment]
Any idea what kind of graphics hardware (open gl support) this machine has?

**Comment by TheCDC** [comment]
I also have this  It issue, but not on all machines. Arcade works as expected as my Surface (Pro?) but not on my Asus N550JK with and Nvidia GTX 850M on neither Windows 10 nor Ubuntu 18.04.

I think I found the problem in `application.py` lines 42-50 by messing with the config arguments. Instantiating my game object with `antialiasing=False` prevents the error but I get a solid black window.

Changing those lines in `application.py` to 

```
       if antialiasing:
            config = pyglet.gl.Config(major_version=3,
                                      minor_version=3,
                                      double_buffer=True,
                                      sample_buffers=1,
                                      samples=16)
        else:
            config = pyglet.gl.Config(major_version=3,
                                      minor_version=3,
                                      double_buffer=True,)
```

prevents the error.

**Comment by mbartelsm** [comment]
@pvcraven it has a GTX 960M with latest drivers, it should have OpenGL support

**Comment by pvcraven** [comment]
Version 2.0.2b1 has been uploaded. Care to test it and see if it works?

**Comment by mbartelsm** [comment]
The issue seems to be fixed, thanks for the prompt response and patch! 😊

**Comment by pvcraven** [comment]
Fixed with 2.0.3 release.

**Comment by itwageslave** [comment]
I am using Fedora and getting the same error
The info on the system
OPENGL Version 3.0 Mesa 19.1.3
Arcade Version 2.0.9
pyglet version 1.4.1

`Traceback (most recent call last):
  File "/home/finn/PycharmProjects/arcadediy/game.py", line 107, in <module>
    main()
  File "/home/finn/PycharmProjects/arcadediy/game.py", line 102, in main
    MyGame(SCREEN_WIDTH, SCREEN_HEIGHT, SCREEN_TITLE)
  File "/home/finn/PycharmProjects/arcadediy/game.py", line 20, in __init__
    super().__init__(width, height, title)
  File "/home/finn/PycharmProjects/arcadediy/venv/lib64/python3.7/site-packages/arcade/application.py", line 53, in __init__
    resizable=resizable, config=config)
  File "/home/finn/PycharmProjects/arcadediy/venv/lib64/python3.7/site-packages/pyglet/window/xlib/__init__.py", line 171, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home/finn/PycharmProjects/arcadediy/venv/lib64/python3.7/site-packages/pyglet/window/__init__.py", line 592, in __init__
    config = screen.get_best_config(config)
  File "/home/finn/PycharmProjects/arcadediy/venv/lib64/python3.7/site-packages/pyglet/canvas/base.py", line 198, in get_best_config
    raise window.NoSuchConfigException()
pyglet.window.NoSuchConfigException

Process finished with exit code 1`

**Comment by pvcraven** [comment]
Needs OpenGL 3.3 or higher. OpenGL ES doesn't work.

**Comment by itwageslave** [comment]
Thanks
