### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'width'

### ISSUE THREAD

**Issue by RichardDally** [pvcraven/arcade#354]
## Bug Report
Example sprite_move_animation.py is buggy.
Tested on master HEAD (ce667a7bca4f249fc29a44b2dd806d77054b6a1d)

### Actual behavior:
$ python -m sprite_move_animation
Traceback (most recent call last):
  File "C:\Python3.6.1\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python3.6.1\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Programming\arcade\arcade\examples\sprite_move_animation.py", line 177, in <module>
    main()
  File "C:\Programming\arcade\arcade\examples\sprite_move_animation.py", line 172, in main
    window.setup()
  File "C:\Programming\arcade\arcade\examples\sprite_move_animation.py", line 93, in setup
    self.player.scale = 0.8
  File "C:\Python3.6.1\lib\site-packages\arcade\sprite.py", line 378, in _set_scale
    self._width = self._texture.width * self._scale
AttributeError: 'NoneType' object has no attribute 'width'

### Expected behavior:
Running successfully the example.

### Steps to reproduce/example code:
$ python -m sprite_move_animation

**Comment by pvcraven** [comment]
Bug appears to have been introduced with check-in for Issue #331, adding the ability to dynamically scale a sprite.

**Comment by pvcraven** [comment]
Need to create a unit-test for animated sprites.

**Comment by RichardDally** [comment]
I'm willing to help but I can't afford reading the whole code :)
What specific module I should read to help fixing this bug ?

**Comment by pvcraven** [comment]
I pushed a commit to fix it. It will be in the next release, hopefully out soon.

**Comment by RichardDally** [comment]
Thank you very much !
