### ISSUE TITLE
Distributing With Pyinstaller On Linux

### ISSUE THREAD

**Issue by isidentical** [pvcraven/arcade#412]
## Bug Report
I have a simple script with no external dependicy except arcade itself and no resource usage. 
### Actual behavior:
When i try to generate an executable with pyInstaller, it raises an error.
```
Traceback (most recent call last):
  File "kanuni.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/home/batuhan/.local/share/virtualenvs/games-lTagmTRo/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/arcade/__init__.py", line 36, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/home/batuhan/.local/share/virtualenvs/games-lTagmTRo/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/arcade/sound.py", line 93, in <module>
  File "site-packages/arcade/sound.py", line 42, in _load_sound_library
  File "site-packages/pyglet_ffmpeg2/loader.py", line 16, in load_ffmpeg
  File "site-packages/pyglet_ffmpeg2/loader.py", line 54, in _locate_binaries
  File "site-packages/pyglet_ffmpeg2/loader.py", line 81, in _ensure_linux_symlinks
IndexError: list index out of range
[5133] Failed to execute script kanuni
```
### Expected behavior:
None
### Steps to reproduce/example code:
```py
git clone git@github.com:isidentical/kanuni.git
cd kanuni
pyinstaller --exclude-module tkinter --onefile --noconsole kanuni.py
./dist/kanuni
```

**Comment by pvcraven** [comment]
Closing. At some point, a deeper dive needs to be done with distribution methods.
