### ISSUE TITLE
arcade and glooey don't play well together

### ISSUE THREAD

**Issue by b3noist** [pvcraven/arcade#468]
Please excuse this rather haphazard issue. I'm a novice and not quite sure if this is even the right place to ask, but I figured I'd try here first anyway.

### Actual behavior:
I'm trying to get a user-editable text area to show in the window using glooey. Following the examples from glooey's docs, I've managed to get that working using a plain-jane pyglet.window.Window. However, after switching that over to arcade.Window, no window shows up and I get a long string of errors when I try to run the code.

```
$ python textexample.py 
Traceback (most recent call last):
  File "C:\Users\***\.virtualenvs\bloop-fK3f2yTm\lib\site-packages\pyglet\graphics\__init__.py", line 452, in _get_domain
    domain = domain_map[key]
KeyError: (('v2f', 'c4B'), 1, False)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "textexample.py", line 9, in <module>
    gui.add(form)
  File "C:\Users\***\.virtualenvs\bloop-fK3f2yTm\lib\site-packages\glooey\containers.py", line 1151, in add
    self.add_front(widget)
  File "C:\Users\***\.virtualenvs\bloop-fK3f2yTm\lib\site-packages\glooey\containers.py", line 1160, in add_front        
    self.insert(widget, layer)
  File "C:\Users\***\.virtualenvs\bloop-fK3f2yTm\lib\site-packages\glooey\containers.py", line 1185, in insert
    self._repack_and_regroup_children()
  File "C:\Users\***\.virtualenvs\bloop-fK3f2yTm\lib\site-packages\glooey\helpers.py", line 82, in wrapped_method
    method(self, *args, **kwargs)
  File "C:\Users\***\.virtualenvs\bloop-fK3f2yTm\lib\site-packages\glooey\widget.py", line 1531, in _repack_and_regroup_children
    self.do_regroup_children()
  File "C:\Users\***\.virtualenvs\bloop-fK3f2yTm\lib\site-packages\glooey\containers.py", line 1235, in do_regroup_children
    child._regroup(self.group)
  File "C:\Users\***\.virtualenvs\bloop-fK3f2yTm\lib\site-packages\glooey\widget.py", line 1498, in _regroup
    self.do_regroup_children()
  File "C:\Users\***\.virtualenvs\bloop-fK3f2yTm\lib\site-packages\glooey\widget.py", line 529, in do_regroup_children
    child._regroup(self.group)
  File "C:\Users\***\.virtualenvs\bloop-fK3f2yTm\lib\site-packages\glooey\widget.py", line 1498, in _regroup
    self.do_regroup_children()
  File "C:\Users\***\.virtualenvs\bloop-fK3f2yTm\lib\site-packages\glooey\containers.py", line 1238, in do_regroup_children
    child._regroup(pyglet.graphics.OrderedGroup(layer, self.group))
  File "C:\Users\***\.virtualenvs\bloop-fK3f2yTm\lib\site-packages\glooey\widget.py", line 1495, in _regroup
    self._draw()
  File "C:\Users\***\.virtualenvs\bloop-fK3f2yTm\lib\site-packages\glooey\helpers.py", line 82, in wrapped_method
    method(self, *args, **kwargs)
  File "C:\Users\***\.virtualenvs\bloop-fK3f2yTm\lib\site-packages\glooey\widget.py", line 1641, in _draw
    self.do_draw()
  File "C:\Users\***\.virtualenvs\bloop-fK3f2yTm\lib\site-packages\glooey\text.py", line 126, in do_draw
    self._layout = self.do_make_new_layout(document, kwargs)
  File "C:\Users\***\.virtualenvs\bloop-fK3f2yTm\lib\site-packages\glooey\text.py", line 425, in do_make_new_layout
    new_caret = pyglet.text.caret.Caret(new_layout, color=self.color[:3])
  File "C:\Users\***\.virtualenvs\bloop-fK3f2yTm\lib\site-packages\pyglet\text\caret.py", line 129, in __init__
    'v2f', ('c4B', colors))
  File "C:\Users\***\.virtualenvs\bloop-fK3f2yTm\lib\site-packages\pyglet\graphics\__init__.py", line 368, in add
    domain = self._get_domain(False, mode, group, formats)
  File "C:\Users\***\.virtualenvs\bloop-fK3f2yTm\lib\site-packages\pyglet\graphics\__init__.py", line 458, in _get_domain
    domain = vertexdomain.create_domain(*formats)
  File "C:\Users\***\.virtualenvs\bloop-fK3f2yTm\lib\site-packages\pyglet\graphics\vertexdomain.py", line 140, in create_domain
    return VertexDomain(attribute_usages)
  File "C:\Users\***\.virtualenvs\bloop-fK3f2yTm\lib\site-packages\pyglet\graphics\vertexdomain.py", line 191, in __init__
    usage=usage, vbo=vbo)
  File "C:\Users\***\.virtualenvs\bloop-fK3f2yTm\lib\site-packages\pyglet\graphics\vertexbuffer.py", line 115, in create_mappable_buffer  
    return MappableVertexBufferObject(size, target, usage)
  File "C:\Users\***\.virtualenvs\bloop-fK3f2yTm\lib\site-packages\pyglet\graphics\vertexbuffer.py", line 389, in __init__
    super(MappableVertexBufferObject, self).__init__(size, target, usage)
  File "C:\Users\***\.virtualenvs\bloop-fK3f2yTm\lib\site-packages\pyglet\graphics\vertexbuffer.py", line 306, in __init__
    glPushClientAttrib(GL_CLIENT_VERTEX_ARRAY_BIT)
  File "C:\Users\***\.virtualenvs\bloop-fK3f2yTm\lib\site-packages\pyglet\gl\lib.py", line 106, in errcheck
    raise GLException(msg)
pyglet.gl.lib.GLException: b'invalid operation'
Exception ignored in: <function VertexDomain.__del__ at 0x0000024E2AFB81F8>
Traceback (most recent call last):
  File "C:\Users\***\.virtualenvs\bloop-fK3f2yTm\lib\site-packages\pyglet\graphics\vertexdomain.py", line 238, in __del__
    for attribute in self.attributes:
AttributeError: 'VertexDomain' object has no attribute 'attributes'
```

### Expected behavior:
It should simply show a window with a black background, editable green text, and a blinking caret.

### Steps to reproduce/example code:
```
import pyglet
import glooey
import arcade

window = arcade.Window()
gui = glooey.Gui(window)
form = glooey.Form()

gui.add(form)
form.set_text("test")

arcade.run()
```

Attempt to run the above code with Python.

**Comment by huooyk** [comment]
Hi, I suggest you take a hard look at the glooey library, or take a hard look at the arcade library, but I'll give you executable code anyway。
`import pyglet
import glooey

window=pyglet.window.Window()
gui = glooey.Gui(window)
form = glooey.Form()

gui.add(form)
form.set_text("test")

pyglet.app.run()`

@pvcraven Please close this issue.

**Comment by pvcraven** [comment]
Closing.
