### ISSUE TITLE
Unable to load the ffmpeg library.

### ISSUE THREAD

**Issue by BenoitPingris** [pvcraven/arcade#493]
## Bug Report
When I import arcade I have an error saying it can't find ffmpeg.

### Actual behavior:
```
$ python
>>> import arcade
Unable to load the ffmpeg library.  list index out of range
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/benoit/.local/lib/python3.7/site-packages/arcade/__init__.py", line 36, in <module>
    from arcade.sound import *
  File "/home/benoit/.local/lib/python3.7/site-packages/arcade/sound.py", line 94, in <module>
    _load_sound_library()
  File "/home/benoit/.local/lib/python3.7/site-packages/arcade/sound.py", line 42, in _load_sound_library
    import pyglet_ffmpeg2
  File "/home/benoit/.local/lib/python3.7/site-packages/pyglet_ffmpeg2/__init__.py", line 5, in <module>
    load_ffmpeg()
  File "/home/benoit/.local/lib/python3.7/site-packages/pyglet_ffmpeg2/loader.py", line 16, in load_ffmpeg
    _locate_binaries()
  File "/home/benoit/.local/lib/python3.7/site-packages/pyglet_ffmpeg2/loader.py", line 55, in _locate_binaries
    _ensure_linux_symlinks(path)
  File "/home/benoit/.local/lib/python3.7/site-packages/pyglet_ffmpeg2/loader.py", line 82, in _ensure_linux_symlinks
    sofile = glob.glob(os.path.join(bin_folder, glob_sofile))[0]
IndexError: list index out of range
```

### Steps to reproduce/example code:
I'm using a virtualenv with pipenv
```bash
$ pipenv --python 3.7
$ pipenv install arcade
$ python
>>> import arcade
[error from above]
```

I have ffmpeg on ny machine.
I'm using Manjaro 18.1.0 Juhraya

**Comment by pvcraven** [comment]
I don't have an easy way to test this.

If you update the library `pyglet_ffmpeg2` to version 0.1.15 it should allow you to run without crashing, but the code won't load ffmpeg and you'll have to use `.wav` files. I need to spend time examining how to find ffmpeg on the linux distributions and load that.

**Comment by BenoitPingris** [comment]
Ok I'll try this, so this issue is more related to pyglet-ffmpeg rather than arcade ?
Thank you

**Comment by pvcraven** [comment]
Yes, pyglet-ffmpeg2.

**Comment by TheCodeSummoner** [comment]
Is this still an issue or resolved? The most recent `pyglet_ffmpeg2` distribution doesn't have the mentioned code anymore.

**Comment by pvcraven** [comment]
Closing, shouldn't generate this error now.
