### ISSUE TITLE
particle_fireworks example is not running with 2.2.5

### ISSUE THREAD

**Issue by SirGnip** [pvcraven/arcade#555]
### Actual behavior:
Running the `examples/particle_fireworks` sample throws this exception on startup:

### Expected behavior:
It runs properly

### Steps to reproduce/example code:
This is on a Windows 10 box running arcade from a git checkout at the `release_2_2_5` tag.

```
$ python -m arcade.examples.particle_fireworks
Traceback (most recent call last):
  File "C:\Users\scott\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\scott\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\cache\repo\arcade\arcade\examples\particle_fireworks.py", line 357, in <module>
    arcade.run()
  File "C:\cache\repo\arcade\arcade\window_commands.py", line 246, in run
    pyglet.app.run()
  File "C:\cache\venv\arcadedev\lib\site-packages\pyglet\app\__init__.py", line 144, in run
    event_loop.run()
  File "C:\cache\venv\arcadedev\lib\site-packages\pyglet\app\base.py", line 175, in run
    self._run()
  File "C:\cache\venv\arcadedev\lib\site-packages\pyglet\app\base.py", line 187, in _run
    timeout = self.idle()
  File "C:\cache\venv\arcadedev\lib\site-packages\pyglet\app\base.py", line 314, in idle
    window.dispatch_event('on_draw')
  File "C:\cache\venv\arcadedev\lib\site-packages\pyglet\window\__init__.py", line 1330, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\cache\venv\arcadedev\lib\site-packages\pyglet\event.py", line 428, in dispatch_event
    self._raise_dispatch_exception(event_type, args, getattr(self, event_type), exception)
  File "C:\cache\venv\arcadedev\lib\site-packages\pyglet\event.py", line 482, in _raise_dispatch_exception
    raise exception
  File "C:\cache\venv\arcadedev\lib\site-packages\pyglet\event.py", line 423, in dispatch_event
    if getattr(self, event_type)(*args):
  File "C:\cache\repo\arcade\arcade\examples\particle_fireworks.py", line 332, in on_draw
    e.draw()
  File "C:\cache\repo\arcade\arcade\emitter.py", line 167, in draw
    self._particles.draw()
  File "C:\cache\repo\arcade\arcade\sprite_list.py", line 803, in draw
    self._calculate_sprite_buffer()
  File "C:\cache\repo\arcade\arcade\sprite_list.py", line 619, in _calculate_sprite_buffer
    calculate_colors()
  File "C:\cache\repo\arcade\arcade\sprite_list.py", line 490, in calculate_colors
    self._sprite_color_data.append(sprite.alpha)
TypeError: integer argument expected, got float
Error in sys.excepthook:

Original exception was:


```

**Comment by pvcraven** [comment]
Fixed with release 2.2.6.
