### ISSUE TITLE
Unable to load ffmpeg dependencies

### ISSUE THREAD

**Issue by AlexMartin17** [pvcraven/arcade#604]
## Bug Report
I cannot load arcade in python3.6 on CentOS6
### Actual behavior:
```
Python 3.6.9 (default, Dec 21 2019, 01:46:29) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-23)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import arcade
Unable to find match for ffmpeg sound library at expected location: /usr/local/lib64/python3.6/site-packages/pyglet_ffmpeg2/linux_x86_64/libavcodec.so.58.*
Unable to find match for ffmpeg sound library at expected location: /usr/local/lib64/python3.6/site-packages/pyglet_ffmpeg2/linux_x86_64/libavformat.so.58.*
Unable to find match for ffmpeg sound library at expected location: /usr/local/lib64/python3.6/site-packages/pyglet_ffmpeg2/linux_x86_64/libswresample.so.3.*
Unable to find match for ffmpeg sound library at expected location: /usr/local/lib64/python3.6/site-packages/pyglet_ffmpeg2/linux_x86_64/libavfilter.so.7.*
Unable to find match for ffmpeg sound library at expected location: /usr/local/lib64/python3.6/site-packages/pyglet_ffmpeg2/linux_x86_64/libavutil.so.56.*
Unable to find match for ffmpeg sound library at expected location: /usr/local/lib64/python3.6/site-packages/pyglet_ffmpeg2/linux_x86_64/libswscale.so.5.*
Unable to load the ffmpeg library.  /usr/lib64/libavutil.so.54: undefined symbol: av_version_info
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pyglet/__init__.py", line 329, in __getattr__
    return getattr(self._module, name)
AttributeError: 'NoneType' object has no attribute 'Source'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/arcade/__init__.py", line 190, in <module>
    from .sound import PlaysoundException
  File "/usr/local/lib/python3.6/site-packages/arcade/sound.py", line 87, in <module>
    def stop_sound(sound: pyglet.media.Source):
  File "/usr/local/lib/python3.6/site-packages/pyglet/__init__.py", line 335, in __getattr__
    __import__(import_name)
  File "/usr/local/lib/python3.6/site-packages/pyglet/media/__init__.py", line 143, in <module>
    add_default_media_codecs()
  File "/usr/local/lib/python3.6/site-packages/pyglet/media/codecs/__init__.py", line 164, in add_default_media_codecs
    if have_ffmpeg():
  File "/usr/local/lib/python3.6/site-packages/pyglet/media/codecs/__init__.py", line 180, in have_ffmpeg
    from . import ffmpeg_lib
  File "/usr/local/lib/python3.6/site-packages/pyglet/media/codecs/ffmpeg_lib/__init__.py", line 36, in <module>
    from .libavcodec import *
  File "/usr/local/lib/python3.6/site-packages/pyglet/media/codecs/ffmpeg_lib/libavcodec.py", line 46, in <module>
    from . import libavutil
  File "/usr/local/lib/python3.6/site-packages/pyglet/media/codecs/ffmpeg_lib/libavutil.py", line 188, in <module>
    avutil.av_version_info.restype = c_char_p
  File "/usr/local/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "/usr/local/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib64/libavutil.so.54: undefined symbol: av_version_info
```

### Steps to reproduce/example code:
```
python3.6
>>>import arcade
```

I have ffmpeg 2.6.8 installed on my machine.

**Comment by pvcraven** [comment]
Closing. Please track under Issue #372.
