### ISSUE TITLE
pyglet.gl.lib.GLException: b'invalid value'

### ISSUE THREAD

**Issue by Scottes** [pvcraven/arcade#627]
Running Windows 10, Python 3.8.2, Arcade 2.3.11, and I'm getting the following error:

Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\arcade\shader.py", line 519, in __init__
    gl.glTexImage2D(
  File "C:\Python38\lib\site-packages\pyglet\gl\lib.py", line 107, in errcheck
    raise GLException(msg)
pyglet.gl.lib.GLException: b'invalid value'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\data\projects\General_Mayhem\general_mayhem.py", line 660, in <module>
    main()
  File "C:\data\projects\General_Mayhem\general_mayhem.py", line 656, in main
    arcade.run()
  File "C:\Python38\lib\site-packages\arcade\window_commands.py", line 250, in run
    pyglet.app.run()
  File "C:\Python38\lib\site-packages\pyglet\app\__init__.py", line 107, in run
    event_loop.run()
  File "C:\Python38\lib\site-packages\pyglet\app\base.py", line 170, in run
    self._run()
  File "C:\Python38\lib\site-packages\pyglet\app\base.py", line 182, in _run
    timeout = self.idle()
  File "C:\Python38\lib\site-packages\pyglet\app\base.py", line 303, in idle
    redraw_all = self.clock.call_scheduled_functions(dt)
  File "C:\Python38\lib\site-packages\pyglet\clock.py", line 292, in call_scheduled_functions
    item.func(now - item.last_ts, *item.args, **item.kwargs)
  File "C:\data\projects\General_Mayhem\general_mayhem.py", line 590, in on_update
    self.enemy_list.update_animation(delta_time)
  File "C:\Python38\lib\site-packages\arcade\sprite_list.py", line 446, in update_animation
    sprite.update_animation(delta_time)
  File "C:\data\projects\General_Mayhem\enemies.py", line 312, in update_animation
    self.texture = self.sprites[current_action][sprite_to_display][facing]
  File "C:\Python38\lib\site-packages\arcade\sprite.py", line 696, in _set_texture2
    sprite_list.update_texture(self)
  File "C:\Python38\lib\site-packages\arcade\sprite_list.py", line 750, in update_texture
    self._calculate_sprite_buffer()
  File "C:\Python38\lib\site-packages\arcade\sprite_list.py", line 681, in _calculate_sprite_buffer
    _calculate_sub_tex_coords()
  File "C:\Python38\lib\site-packages\arcade\sprite_list.py", line 635, in _calculate_sub_tex_coords
    self._texture = shader.texture(
  File "C:\Python38\lib\site-packages\arcade\shader.py", line 545, in texture
    return Texture(size, component, data)
  File "C:\Python38\lib\site-packages\arcade\shader.py", line 524, in __init__
    raise gl.GLException(f"Unable to create texture. {gl.GL_MAX_TEXTURE_SIZE} {size}")
pyglet.gl.lib.GLException: Unable to create texture. 3379 (32872, 128)

The issue *seems* to occur because I'm using a number of different enemy sprites.
If I have the Hero and 16 instances of one enemy running around it's fine.
If I have the Hero and 1 to 16 instances each of 2 different enemies running around it's fine.
If I have the Hero and 1 instance each of 3 different enemies running around it crashes after anywhere from 12 to 95 seconds (out of ~12 test runs). The time-to-crash doesn't change if I add more instances or a fourth different enemy.
The enemy itself doesn't matter - I've tried 8 instances of each enemy without a crash, but 3 or more different enemies at once causes the crash eventually.

The Hero consists of 160 PNgs, each enemy is 70 PNGs. All are between 128x128 and 160x128.
Map is 16x32 blocks of 128x128 textures totaling 4096 x 2048 pixels.
Memory usage is about 145 MB, CPU 3-4%, GPU about 20-22%.

I've tried googling for the error "pyglet.gl.lib.GLException: b'invalid value'" but they seem to be issues with image size or specific to certain applications. I didn't find anything that seemed pertinent to me.

Any other tips on debugging this would be appreciated.

**Comment by pvcraven** [comment]
This is Issue #332, there's only so many different textures that can be associated with a SpriteList. This needs to be improved on.

**Comment by HiranChaudhuri** [comment]
Regardless whether the limitation can be improved (moved to bigger values), would it be possible to detect the situation and emit an explaining error message? Something like "Out of sprite texture memory" or "Too many textures"?

**Comment by Scottes** [comment]
I agree.
Making an assumption from the error "pyglet.gl.lib.GLException: Unable to create texture. 3379 (32872, 128)" it would seem like the SpriteList can be a maximum of 32,872 pixels wide - which is (as an example) slightly more than 256 textures that are each 128 wide. If that's correct, then an informative error could possibly be thrown when loading the textures into the SpriteList rather than in-game at some random time when it attempts to load a sprite that is beyond that limit.

**Comment by pvcraven** [comment]
The width of the texture depends on the graphics card and driver in use.

Paul Vincent Craven

**Comment by pvcraven** [comment]
Want to do me a favor? Please try Arcade 2.3.12b1. It doesn't make a better error message, but it should support WAY more textures in a sprite list.

**Comment by Scottes** [comment]
I'll give it shot. I'll have to roll back quite a ways, but that should be possible. Time to learn a little more git...

**Comment by Scottes** [comment]
I cloned arcade and rolled back my game to the submit before I worked around this issue. I confirmed that both version were as-expected, and ran my game.

It looks good. Previous tests never ran more than 95 seconds before crashing, but with the latest Arcade it ran for 13+ minutes without a crash. Ship it! :-)

**Comment by einarf** [comment]
Should probably try the `2.3.12b1` release on PyPI instead of using master branch. I don't think that code is pushed.

**Comment by Scottes** [comment]
I did not find a 2.3.11b version on PyPi or Github, so I cloned it. But I can test again if you give me a tip on how to get the official/published 2.3.11b.

**Comment by einarf** [comment]
https://pypi.org/project/arcade/2.3.12b2/#history
```
pip install arcade==2.3.12b1
pip install arcade==2.3.12b2
```

**Comment by Scottes** [comment]
Ah. I just tried a pip search and didn't see any other versions. Thanks for the info.

**Comment by pvcraven** [comment]
Should be fixed, release 2.3.12 was just pushed out.
