### ISSUE TITLE
2.4.a1 can't find resource

### ISSUE THREAD

**Issue by Scottes** [pvcraven/arcade#642]
With 2.3.15 installed my game works fine, but if I install 2.4.a1 it throws an error about not finding an image that I use.

C:\data\projects\General_Mayhem>.\general_mayhem.py
Traceback (most recent call last):
  File "C:\data\projects\General_Mayhem\general_mayhem.py", line 819, in <module>
    main()
  File "C:\data\projects\General_Mayhem\general_mayhem.py", line 812, in main
    window = MyGame()
  File "C:\data\projects\General_Mayhem\general_mayhem.py", line 97, in __init__
    self.laser_red_hit_texture_list = effects.Explosions.laser_red_hit_sprites(self)
  File "C:\data\projects\General_Mayhem\effects.py", line 47, in laser_red_hit_sprites
    texture_list = arcade.load_spritesheet(filename,
  File "C:\Python38\lib\site-packages\arcade\texture.py", line 388, in load_spritesheet
    file_name = resolve_resource_path(file_name)
  File "C:\Python38\lib\site-packages\arcade\resources\__init__.py", line 27, in resolve_resource_path
    raise FileNotFoundError(f"Cannot locate resource : {path}")
FileNotFoundError: Cannot locate resource : C:\Python38\lib\site-packages\arcade\resources\pics\projectiles\laser_red_hit.png

I seem to recall seeing some submit(s) around the path. Do I need to update my code?

Code in question is this:
        filename = "pics/projectiles/laser_red_hit.png"
        # Load the explosions from a sprite sheet
        texture_list = arcade.load_spritesheet(filename,
            sprite_width, sprite_height, columns, count)

I'm not sure why it's looking in C:\Python38\lib\site-packages\arcade\resources as a base path. It should be looking from the cwd since I don't have ":resources:" in the filename,

**Comment by pvcraven** [comment]
Yes, it should not be flipping to resources as a base path. That's a bug I need to fix. Thanks for reporting.

**Comment by pvcraven** [comment]
2.4a2 is out. I think it fixes it.

**Comment by Scottes** [comment]
Now there's a different issue.

Successfully installed arcade-2.4a2

C:\data\projects\General_Mayhem>.\general_mayhem.py
Traceback (most recent call last):
  File "C:\data\projects\General_Mayhem\general_mayhem.py", line 819, in <module>
    main()
  File "C:\data\projects\General_Mayhem\general_mayhem.py", line 812, in main
    window = MyGame()
  File "C:\data\projects\General_Mayhem\general_mayhem.py", line 42, in __init__
    super().__init__(SCREEN_WIDTH, SCREEN_HEIGHT, SCREEN_TITLE)
  File "C:\Python38\lib\site-packages\arcade\application.py", line 112, in __init__
    self._ctx = shader.Context(self)
  File "C:\Python38\lib\site-packages\arcade\shader.py", line 1854, in __init__
    self.shape_line_program = self.load_program(
  File "C:\Python38\lib\site-packages\arcade\shader.py", line 2039, in load_program
    vertex_shader_src = resources.resolve_resource_path(vertex_shader).read_text()
  File "C:\Python38\lib\site-packages\arcade\resources\__init__.py", line 29, in resolve_resource_path
    raise FileNotFoundError(f"Cannot locate resource : {path}")
FileNotFoundError: Cannot locate resource : C:\Python38\lib\site-packages\arcade\resources\shaders\shapes\line\unbuffered_vs.glsl

C:\data\projects\General_Mayhem>

**Comment by pvcraven** [comment]
2.4a3 should include those now.

**Comment by Scottes** [comment]
Now I can play my game, but it's throwing errors in the background:

Successfully uninstalled arcade-2.4a2
Successfully installed arcade-2.4a3

C:\data\projects\General_Mayhem>.\general_mayhem.py
C:\Python38\lib\site-packages\arcade\shader.py:2165: UserWarning: buffer allocations passed threshold (1000). created = 1000, freed = 918 = 82 active.
  warn((
C:\Python38\lib\site-packages\arcade\shader.py:2165: UserWarning: buffer allocations passed threshold (1000). created = 2000, freed = 1920 = 80 active.
  warn((
C:\Python38\lib\site-packages\arcade\shader.py:2165: UserWarning: buffer allocations passed threshold (1000). created = 3000, freed = 2922 = 78 active.
  warn((

**Comment by pvcraven** [comment]
Oh, that's debug info. Ignore, it should be gone in release version.

**Comment by Scottes** [comment]
OK, cool. It looks good then, and plays fine.

It also looks like an anomaly that I've been seeing was fixed, too, so that's great. I seem to recall something about a submit for the physics engine glitching...? Anyway, I'm not longer seeing something I used to see frequently, but thought it was my code. So, kudos on that too.

**Comment by pvcraven** [comment]
Excellent, glad that fix worked for you.
