### ISSUE TITLE
Solitaire Tutorial Issues

### ISSUE THREAD

**Issue by sarmad-apprenti** [pvcraven/arcade#695]
I really like the library and all the documentation available. I was trying to go through the example in this link on the [Solitaire tutorial](https://arcade.academy/tutorials/card_game/index.html) and I ran into several issues. Just curious if this tutorial up-to-date? 

It seems to reference several resource/assets that no longer exit in this project under [resources/images](https://github.com/pvcraven/arcade/tree/master/arcade/resources/images) (e.g. all [the cards assets](https://arcade.academy/resources.html?highlight=images#resources-images-cards)).

Besides hitting `[Errno 2]` on assets I'm currently hitting this issue as well: 

```
Traceback (most recent call last):
  File "solitaire_11.py", line 403, in <module>
    main()
  File "solitaire_11.py", line 398, in main
    window.setup()
  File "solitaire_11.py", line 177, in setup
    self.card_list[pos1], self.card_list[pos2] = self.card_list[pos2], self.card_list[pos1]
TypeError: 'SpriteList' object does not support item assignment

```
Can you please let me know if that's expected behaviour due to the tutorial example being out-of-date with new library changes?

**Comment by pvcraven** [comment]
Sounds like you've got the non-alpha version of the library. You need 2.4a9. 2.3.15 gets installed by default, so `pip install arcade==2.4a9` I think will work to install the alpha version.

**Comment by sarmad-apprenti** [comment]
It's working now on the alpha version. Thanks @pvcraven closing this issue 👍
