### ISSUE TITLE
macOS: Closing the window causes an error and a 'quit unexpectedly' message

### ISSUE THREAD

**Issue by SuperPupperDoggo** [pvcraven/arcade#709]
## Bug Report
macOS: Closing the window causes an error and a 'quit unexpectedly' message
### Actual behavior:

Will quit as expected but displays an error in the console, and shows a 'Python quit unexpectedly' message. This is what the console shows:
```
2020-06-22 10:18:56.787 Python[79533:6969801] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to (null)
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'
  File "/Users/USER/PycharmProjects/untitled/venv/lib/python3.7/site-packages/pyglet/libs/darwin/cocoapy/runtime.py", line 1120, in objc_method
    args = convert_method_arguments(encoding, args)
  File "/Users/USER/PycharmProjects/untitled/venv/lib/python3.7/site-packages/pyglet/libs/darwin/cocoapy/runtime.py", line 1000, in convert_method_arguments
    new_args.append(ObjCInstance(a))
  File "/Users/USER/PycharmProjects/untitled/venv/lib/python3.7/site-packages/pyglet/libs/darwin/cocoapy/runtime.py", line 921, in __new__
    if not isinstance(object_ptr, c_void_p):
RecursionError: maximum recursion depth exceeded while calling a Python object

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)`
```

### Expected behavior:

To quit normally(as in, without crashing)

### Steps to reproduce/example code:

1. Make a basic program(as an example, here's my code):
```
import arcade
arcade.open_window(600,600,"Drawing Example")
arcade.set_background_color(arcade.csscolor.SKY_BLUE)
arcade.start_render()
arcade.draw_lrtb_rectangle_filled(0, 599, 300, 0, arcade.csscolor.GREEN)
arcade.draw_rectangle_filled(100, 320, 20, 60, arcade.csscolor.SIENNA)
arcade.draw_circle_filled(100, 350, 30, arcade.csscolor.DARK_GREEN)
arcade.draw_rectangle_filled(200, 320, 20, 60, arcade.csscolor.SIENNA)
arcade.draw_ellipse_filled(200, 370, 60, 80, arcade.csscolor.DARK_GREEN)
arcade.draw_rectangle_filled(300, 320, 20, 60, arcade.csscolor.SIENNA)
arcade.draw_arc_filled(300, 340, 60, 100, arcade.csscolor.DARK_GREEN, 0, 180)
arcade.draw_rectangle_filled(400, 320, 20, 60, arcade.csscolor.SIENNA)
arcade.draw_triangle_filled(400, 400, 370, 320, 430, 320, arcade.csscolor.DARK_GREEN)
arcade.finish_render()
arcade.run()
```

2. Run the code(on macOS)

3. Close the window

**Comment by SuperPupperDoggo** [comment]
Apologies for the several edits, I'm unfamiliar with markdown

**Comment by einarf** [comment]
I think this was fixed in pyglet 1.5.6. Check what version you have installed.

**Comment by einarf** [comment]
* Upgrade arcade to 2.4 alpha: `pip install arcade==2.4a9`
* Upgrade pyglet to 1.5.6 or later

**Comment by SuperPupperDoggo** [comment]
Thanks!
