### ISSUE TITLE
Can't run arcade: no module named 'numpy'

### ISSUE THREAD

**Issue by Annika18** [pvcraven/arcade#725]
## Bug Report
Hi. I'm new to arcade and trying to test its features. When I try to run any file that makes use of arcade (ie, uses 'import arcade'), I get the following error:

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/Users/USERNAME/Library/Python/3.7/lib/python/site-packages/arcade/__init__.py", line 53, in <module>
    from .window_commands import close_window
  File "/Users/USERNAME/Library/Python/3.7/lib/python/site-packages/arcade/window_commands.py", line 11, in <module>
    import numpy as np
**ModuleNotFoundError: No module named 'numpy'**

### Expected behavior:
This should run an arcade script from the examples folder

### Steps to reproduce/example code:
python3 -m arcade.examples.slime_invaders

## Help please:
I have tried this with multiple arcade example files, including an app of my own. I most definitely have numpy downloaded and they are in the same environment (I verified this with pip freeze). I'm super confused, any help troubleshooting would be appreciated.

**Comment by einarf** [comment]
Something wrong might have happened during the install? Try this:
```bash
python3 -m pip install -I arcade
```
