### ISSUE TITLE
Arcade example errors

### ISSUE THREAD

**Issue by danboid** [pvcraven/arcade#98]
Today I tried running the various Arcade examples that come with the git repo under Arch Linux x64 with Python 3.6.0. A number of the examples, such as the basketball and pymunk-related ones wouldn't even start (eg missing modules - should pymunk be included?) whereas sprite_move_animation.py starts but crashes as soon as I push the up or down arrow keys. I have attached a terminal log of the various errors I encountered trying to run the examples.

I was quite disappointed the sprite_move_animation.py example didn't work properly as sprite animation is THE feature that made me rewrite my first attempt at a python game in Arcade instead of pygame so I'm hoping that one is an easy-ish fix!

**Comment by danboid** [comment]
$ python sprite_move_animation.py 
Traceback (most recent call last):
  File "sprite_move_animation.py", line 151, in <module>
    main()
  File "sprite_move_animation.py", line 147, in main
    arcade.run()
  File "/usr/lib/python3.6/site-packages/arcade/window_commands.py", line 203, in run
    pyglet.app.run()
  File "/usr/lib/python3.6/site-packages/pyglet/app/__init__.py", line 143, in run
    event_loop.run()
  File "/usr/lib/python3.6/site-packages/pyglet/app/base.py", line 136, in run
    self._run_estimated()
  File "/usr/lib/python3.6/site-packages/pyglet/app/base.py", line 165, in _run_estimated
    timeout = self.idle()
  File "/usr/lib/python3.6/site-packages/pyglet/app/base.py", line 274, in idle
    redraw_all = self.clock.call_scheduled_functions(dt)
  File "/usr/lib/python3.6/site-packages/pyglet/clock.py", line 309, in call_scheduled_functions
    item.func(ts - item.last_ts, *item.args, **item.kwargs)
  File "sprite_move_animation.py", line 132, in animate
    self.all_sprites_list.update_animation()
  File "/usr/lib/python3.6/site-packages/arcade/sprite.py", line 539, in update_animation
    sprite.update_animation()
  File "/usr/lib/python3.6/site-packages/arcade/sprite.py", line 693, in update_animation
    if self.cur_texture_index >= len(texture_list):
TypeError: object of type 'NoneType' has no len()


$ python ./basketball.py 
Traceback (most recent call last):
  File "./basketball.py", line 92, in <module>
    on_draw.ball = arcade.Circle(236, 105, 20, arcade.color.ORANGE)
AttributeError: module 'arcade' has no attribute 'Circle'


python ./platformer.py 
Traceback (most recent call last):
  File "./platformer.py", line 13, in <module>
    class PlayerSprite(arcade.PlatformerSpriteSheetSprite):
AttributeError: module 'arcade' has no attribute 'PlatformerSpriteSheetSprite'

$ python pymunk_box_stacks.py 
Traceback (most recent call last):
  File "pymunk_box_stacks.py", line 2, in <module>
    import pymunk
ModuleNotFoundError: No module named 'pymunk'
$ python ./pymunk_box_stacks.py 
Traceback (most recent call last):
  File "./pymunk_box_stacks.py", line 2, in <module>
    import pymunk
ModuleNotFoundError: No module named 'pymunk'

$ python sunny_day.py 
Traceback (most recent call last):
  File "sunny_day.py", line 23, in <module>
    on_draw.hills = arcade.Ellipse(10, 100, 250, 200, arcade.color.GREEN)
AttributeError: module 'arcade' has no attribute 'Ellipse'


$ python test_circles.py 
Traceback (most recent call last):
  File "test_circles.py", line 33, in <module>
    arcade.run()
  File "/usr/lib/python3.6/site-packages/arcade/window_commands.py", line 203, in run
    pyglet.app.run()
  File "/usr/lib/python3.6/site-packages/pyglet/app/__init__.py", line 143, in run
    event_loop.run()
  File "/usr/lib/python3.6/site-packages/pyglet/app/base.py", line 136, in run
    self._run_estimated()
  File "/usr/lib/python3.6/site-packages/pyglet/app/base.py", line 165, in _run_estimated
    timeout = self.idle()
  File "/usr/lib/python3.6/site-packages/pyglet/app/base.py", line 274, in idle
    redraw_all = self.clock.call_scheduled_functions(dt)
  File "/usr/lib/python3.6/site-packages/pyglet/clock.py", line 309, in call_scheduled_functions
    item.func(ts - item.last_ts, *item.args, **item.kwargs)
  File "test_circles.py", line 11, in on_draw
    arcade.draw_small_filled_circle(300, 100, arcade.color.YELLOW)
AttributeError: module 'arcade' has no attribute 'draw_small_filled_circle'

$ python Testing_shapes.py 
Traceback (most recent call last):
  File "Testing_shapes.py", line 30, in <module>
    on_draw.rectangle = arcade.Rectangle(400, 100, 35, 50, arcade.color.PURPLE)
AttributeError: module 'arcade' has no attribute 'Rectangle'

**Comment by pauleveritt** [comment]
You're right, some of those examples are out-of-date. Do you think we should do one-ticket-per-example, or one ticket for all of them?

**Comment by danboid** [comment]
I'm note sure about the sprite_move_animation.py bug - that looks as if it could be a pyglet error and might warrant its own ticket but my wild guess, without having tried to debug any of them, would be that they should be easy enough (for the other Paul, at least) to fix and so one ticket should be sufficient?

Prof. Paul would be able to make a better judgement than me, I'm sure, so I'll let him decide how this should be tackled.

**Comment by pvcraven** [comment]
sprite_move_animation.py isn't a bug, looks like the images  that the program depends on are not available from where you are running it. See how there's an images directory here:

https://github.com/pvcraven/arcade/tree/master/examples

Make sure you have those images.

**Comment by pvcraven** [comment]
The other two programs use items that didn't make it into the API and need to be removed. Thanks.

**Comment by danboid** [comment]
Hi Paul

Yes, I do have all those images as I cloned the entire repo. It seems to be loading most of the images fine as I can move the player left and right but not up or down.

Have you tried running it yourself under Linux with python 3.6.0 such as in Arch? Does it work for you under a similar environment?

The easiest way to install an Arch based OS is with Antergos.

I installed arcade via pip and pip installed pyglet etc as dependencies, then I cloned the repo to try the examples.

**Comment by danboid** [comment]
I've opened a ticket for AVbin that is closely related to this one which is a showstopper for using AVbin on non-Intel platforms ie anything you can't install the AVbin binary installers on such as ARM Linux.

Your input would be appreciated, if you can improve or add to my bug report.

https://github.com/AVbin/AVbin/issues/64

**Comment by danboid** [comment]
@pvcraven Should arcade work with avbin git?

**Comment by pvcraven** [comment]
Outdated examples removed.

**Comment by mrwree14** [comment]
i had a question, i started working on your platformer tutorial i got all the way to the tiled map editor. i got tiled, made a map, when i try running the program i get:

  my_map = arcade.tilemap.read_tmx(map_name)
AttributeError: module 'arcade' has no attribute 'tilemap'

i have re-done the whole thing twice now thinking i did something wrong. i looked up the API package and found "arcade.tilemap.read_tmx".  have you come across this? is there a solution or something i'm missing?

**Comment by urdaibayc** [comment]
Hello guys, I found some related issue. 
`Traceback (most recent call last):
  File "arcade_test.py", line 576, in <module>
    main()
  File "arcade_test.py", line 571, in main
    window.setup()
  File "arcade_test.py", line 274, in setup
    self.tile_map = arcade.load_tilemap(map_name, TILE_SCALING, layer_options)
AttributeError: module 'arcade' has no attribute 'load_tilemap'`

this is my setup:
`Python 3.8.10 (default, Jun  2 2021, 10:49:15)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import arcade
>>> print(arcade.VERSION)
2.5.7`

Greetings

**Comment by Cleptomania** [comment]
@urdaibayc 

We accidentally pushed the docs for the upcoming 2.6 release that isn't out yet to the live site. We are working on a solution to having versioned documentation, but as of right now the docs that are published don't work with the current release of Arcade, they are intended for Arcade 2.6 that's being released later this summer.

**Comment by urdaibayc** [comment]
@Cleptomania 

Thanks!
